UNIFORM_SLEEVES(cwr3_b_uniform_rdf_usmc,cwr3_b_uniform_rdf_rolled_usmc);
UNIFORM_SLEEVES(cwr3_b_uniform_og107_usmc,cwr3_b_uniform_og107_rolled_usmc);
UNIFORM_SLEEVES(cwr3_b_uniform_m81_woodland_usmc,cwr3_b_uniform_m81_woodland_rolled_usmc);

UNIFORM_GLOVES_ROLLED(cwr3_b_uniform_m65_woodland_usmc,cwr3_b_uniform_m65_woodland_gloves_usmc,cwr3_b_uniform_m65_woodland_rolled_usmc,cwr3_b_uniform_m65_woodland_rolled_gloves_usmc);
UNIFORM_GLOVES_ROLLED(cwr3_b_uniform_m65_og107_usmc,cwr3_b_uniform_m65_og107_gloves_usmc,cwr3_b_uniform_m65_og107_rolled_usmc,cwr3_b_uniform_m65_og107_rolled_gloves_usmc);
UNIFORM_GLOVES_ROLLED(cwr3_b_uniform_m65_rdf_usmc,cwr3_b_uniform_m65_rdf_gloves_usmc,cwr3_b_uniform_m65_rdf_rolled_usmc,cwr3_b_uniform_m65_rdf_rolled_gloves_usmc);
