HELMET_GOGGLES_COMPONENT(cwr3_b_headgear_m1_m81_woodland_usmc,cwr3_b_headgear_m1_goggles_m81_woodland_usmc,cwr3_b_facewear_goggles);
HELMET_GOGGLES_COMPONENT(cwr3_b_headgear_m1_mitchell_usmc,cwr3_b_headgear_m1_goggles_mitchell_usmc,cwr3_b_facewear_goggles);
HELMET_GOGGLES_COMPONENT(cwr3_b_headgear_m1_rdf_usmc,cwr3_b_headgear_m1_goggles_rdf_usmc,cwr3_b_facewear_goggles);

HELMET_GOGGLES_COMPONENT(cwr3_b_headgear_pasgt_m81_woodland_usmc,cwr3_b_headgear_pasgt_m81_woodland_usmc_goggles,cwr3_b_facewear_goggles);
HELMET_GOGGLES_COMPONENT(cwr3_b_headgear_pasgt_m81_woodland_usmc_rhino,cwr3_b_headgear_pasgt_m81_woodland_usmc_rhino_goggles,cwr3_b_facewear_goggles);
