UNIFORM_GLOVES_ROLLED(Flex_CUP_FIN_Combat_Uniform,Flex_CUP_FIN_Combat_Uniform_Gloves,Flex_CUP_FIN_Combat_Uniform_Rolled,Flex_CUP_FIN_Combat_Uniform_Gloves_Rolled);

UNIFORM_GLOVES_ROLLED2(Flex_CUP_FIN_Combat_Uniform_Pads,Flex_CUP_FIN_Combat_Uniform_Pads_Gloves,Flex_CUP_FIN_Combat_Uniform_Pads_Rolled);

UNIFORM_GLOVES(Flex_CUP_FIN_Combat_Uniform_Tshirt,Flex_CUP_FIN_Combat_Uniform_Tshirt_Gloves);
