#define USP_UNIFORM_KP_GL(UniformBase,UniformKneepads1,UniformKneepads2,UniformGloves1,UniformGloves2,UniformKneepads1Gloves1,UniformKneepads1Gloves2,UniformKneepads2Gloves1,UniformKneepads2Gloves2)\
class UniformBase: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformKneepads1 {};\
        class UniformKneepads2 {};\
        class UniformGloves1 {};\
        class UniformGloves2 {};\
    };\
};\
class UniformKneepads1: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads1Gloves1 {};\
        class UniformKneepads1Gloves2 {};\
    };\
};\
class UniformKneepads2: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads2Gloves1 {};\
        class UniformKneepads2Gloves2 {};\
    };\
};\
class UniformGloves1: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads1Gloves1 {};\
        class UniformKneepads2Gloves2 {};\
    };\
};\
class UniformGloves2: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads1Gloves2 {};\
        class UniformKneepads1Gloves2 {};\
    };\
}

USP_UNIFORM_KP_GL(USP_RUGBY_G3C           ,USP_RUGBY_G3C_KP           ,USP_RUGBY_G3C_KP2           ,USP_RUGBY_G3C_KP_MX          ,USP_RUGBY_G3C_KP_OR           ,USP_RUGBY_G3C_KP2_MX           ,USP_RUGBY_G3C_KP2_OR);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_AMCU  ,USP_RUGBY_G3C_KP_BLK_AMCU  ,USP_RUGBY_G3C_KP2_BLK_AMCU  ,USP_RUGBY_G3C_KP_MX_BLK_AMCU ,USP_RUGBY_G3C_KP_OR_BLK_AMCU  ,USP_RUGBY_G3C_KP2_MX_BLK_AMCU  ,USP_RUGBY_G3C_KP2_OR_BLK_AMCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_AOR1  ,USP_RUGBY_G3C_KP_BLK_AOR1  ,USP_RUGBY_G3C_KP2_BLK_AOR1  ,USP_RUGBY_G3C_KP_MX_BLK_AOR1 ,USP_RUGBY_G3C_KP_OR_BLK_AOR1  ,USP_RUGBY_G3C_KP2_MX_BLK_AOR1  ,USP_RUGBY_G3C_KP2_OR_BLK_AOR1);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_AOR2  ,USP_RUGBY_G3C_KP_BLK_AOR2  ,USP_RUGBY_G3C_KP2_BLK_AOR2  ,USP_RUGBY_G3C_KP_MX_BLK_AOR2 ,USP_RUGBY_G3C_KP_OR_BLK_AOR2  ,USP_RUGBY_G3C_KP2_MX_BLK_AOR2  ,USP_RUGBY_G3C_KP2_OR_BLK_AOR2);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_DCU   ,USP_RUGBY_G3C_KP_BLK_DCU   ,USP_RUGBY_G3C_KP2_BLK_DCU   ,USP_RUGBY_G3C_KP_MX_BLK_DCU  ,USP_RUGBY_G3C_KP_OR_BLK_DCU   ,USP_RUGBY_G3C_KP2_MX_BLK_DCU   ,USP_RUGBY_G3C_KP2_OR_BLK_DCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_GRY   ,USP_RUGBY_G3C_KP_BLK_GRY   ,USP_RUGBY_G3C_KP2_BLK_GRY   ,USP_RUGBY_G3C_KP_MX_BLK_GRY  ,USP_RUGBY_G3C_KP_OR_BLK_GRY   ,USP_RUGBY_G3C_KP2_MX_BLK_GRY   ,USP_RUGBY_G3C_KP2_OR_BLK_GRY);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_KHK   ,USP_RUGBY_G3C_KP_BLK_KHK   ,USP_RUGBY_G3C_KP2_BLK_KHK   ,USP_RUGBY_G3C_KP_MX_BLK_KHK  ,USP_RUGBY_G3C_KP_OR_BLK_KHK   ,USP_RUGBY_G3C_KP2_MX_BLK_KHK   ,USP_RUGBY_G3C_KP2_OR_BLK_KHK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_M81   ,USP_RUGBY_G3C_KP_BLK_M81   ,USP_RUGBY_G3C_KP2_BLK_M81   ,USP_RUGBY_G3C_KP_MX_BLK_M81  ,USP_RUGBY_G3C_KP_OR_BLK_M81   ,USP_RUGBY_G3C_KP2_MX_BLK_M81   ,USP_RUGBY_G3C_KP2_OR_BLK_M81);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MC    ,USP_RUGBY_G3C_KP_BLK_MC    ,USP_RUGBY_G3C_KP2_BLK_MC    ,USP_RUGBY_G3C_KP_MX_BLK_MC   ,USP_RUGBY_G3C_KP_OR_BLK_MC    ,USP_RUGBY_G3C_KP2_MX_BLK_MC    ,USP_RUGBY_G3C_KP2_OR_BLK_MC);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCB   ,USP_RUGBY_G3C_KP_BLK_MCB   ,USP_RUGBY_G3C_KP2_BLK_MCB   ,USP_RUGBY_G3C_KP_MX_BLK_MCB  ,USP_RUGBY_G3C_KP_OR_BLK_MCB   ,USP_RUGBY_G3C_KP2_MX_BLK_MCB   ,USP_RUGBY_G3C_KP2_OR_BLK_MCB);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCD   ,USP_RUGBY_G3C_KP_BLK_MCD   ,USP_RUGBY_G3C_KP2_BLK_MCD   ,USP_RUGBY_G3C_KP_MX_BLK_MCD  ,USP_RUGBY_G3C_KP_OR_BLK_MCD   ,USP_RUGBY_G3C_KP2_MX_BLK_MCD   ,USP_RUGBY_G3C_KP2_OR_BLK_MCD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCT   ,USP_RUGBY_G3C_KP_BLK_MCT   ,USP_RUGBY_G3C_KP2_BLK_MCT   ,USP_RUGBY_G3C_KP_MX_BLK_MCT  ,USP_RUGBY_G3C_KP_OR_BLK_MCT   ,USP_RUGBY_G3C_KP2_MX_BLK_MCT   ,USP_RUGBY_G3C_KP2_OR_BLK_MCT);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCW   ,USP_RUGBY_G3C_KP_BLK_MCW   ,USP_RUGBY_G3C_KP2_BLK_MCW   ,USP_RUGBY_G3C_KP_MX_BLK_MCW  ,USP_RUGBY_G3C_KP_OR_BLK_MCW   ,USP_RUGBY_G3C_KP2_MX_BLK_MCW   ,USP_RUGBY_G3C_KP2_OR_BLK_MCW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MM14  ,USP_RUGBY_G3C_KP_BLK_MM14  ,USP_RUGBY_G3C_KP2_BLK_MM14  ,USP_RUGBY_G3C_KP_MX_BLK_MM14 ,USP_RUGBY_G3C_KP_OR_BLK_MM14  ,USP_RUGBY_G3C_KP2_MX_BLK_MM14  ,USP_RUGBY_G3C_KP2_OR_BLK_MM14);

USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MPD   ,USP_RUGBY_G3C_KP_BLK_MPD   ,USP_RUGBY_G3C_KP2_BLK_MPD   ,USP_RUGBY_G3C_KP_MX_BLK_MPD  ,USP_RUGBY_G3C_KP_OR_BLK_MPD   ,USP_RUGBY_G3C_KP2_MX_BLK_MPD   ,USP_RUGBY_G3C_KP2_OR_BLK_MPD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MPW   ,USP_RUGBY_G3C_KP_BLK_MPW   ,USP_RUGBY_G3C_KP2_BLK_MPW   ,USP_RUGBY_G3C_KP_MX_BLK_MPW  ,USP_RUGBY_G3C_KP_OR_BLK_MPW   ,USP_RUGBY_G3C_KP2_MX_BLK_MPW   ,USP_RUGBY_G3C_KP2_OR_BLK_MPW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MTN   ,USP_RUGBY_G3C_KP_BLK_MTN   ,USP_RUGBY_G3C_KP2_BLK_MTN   ,USP_RUGBY_G3C_KP_MX_BLK_MTN  ,USP_RUGBY_G3C_KP_OR_BLK_MTN   ,USP_RUGBY_G3C_KP2_MX_BLK_MTN   ,USP_RUGBY_G3C_KP2_OR_BLK_MTN);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MTP   ,USP_RUGBY_G3C_KP_BLK_MTP   ,USP_RUGBY_G3C_KP2_BLK_MTP   ,USP_RUGBY_G3C_KP_MX_BLK_MTP  ,USP_RUGBY_G3C_KP_OR_BLK_MTP   ,USP_RUGBY_G3C_KP2_MX_BLK_MTP   ,USP_RUGBY_G3C_KP2_OR_BLK_MTP);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_NAV   ,USP_RUGBY_G3C_KP_BLK_NAV   ,USP_RUGBY_G3C_KP2_BLK_NAV   ,USP_RUGBY_G3C_KP_MX_BLK_NAV  ,USP_RUGBY_G3C_KP_OR_BLK_NAV   ,USP_RUGBY_G3C_KP2_MX_BLK_NAV   ,USP_RUGBY_G3C_KP2_OR_BLK_NAV);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_RBS   ,USP_RUGBY_G3C_KP_BLK_RBS   ,USP_RUGBY_G3C_KP2_BLK_RBS   ,USP_RUGBY_G3C_KP_MX_BLK_RBS  ,USP_RUGBY_G3C_KP_OR_BLK_RBS   ,USP_RUGBY_G3C_KP2_MX_BLK_RBS   ,USP_RUGBY_G3C_KP2_OR_BLK_RBS);