#define USP_UNIFORM_KP_GL(UniformBase,UniformKneepads1,UniformKneepads2,UniformGloves1,UniformGloves2,UniformKneepads1Gloves1,UniformKneepads1Gloves2,UniformKneepads2Gloves1,UniformKneepads2Gloves2)\
class UniformBase: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformKneepads1 {};\
        class UniformKneepads2 {};\
        class UniformGloves1 {};\
        class UniformGloves2 {};\
    };\
};\
class UniformKneepads1: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads1Gloves1 {};\
        class UniformKneepads1Gloves2 {};\
    };\
};\
class UniformKneepads2: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads2Gloves1 {};\
        class UniformKneepads2Gloves2 {};\
    };\
};\
class UniformGloves1: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads1Gloves1 {};\
        class UniformKneepads2Gloves2 {};\
    };\
};\
class UniformGloves2: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        class UniformKneepads1Gloves2 {};\
        class UniformKneepads1Gloves2 {};\
    };\
}


//Rugby Variants
USP_UNIFORM_KP_GL(USP_RUGBY_G3C          ,USP_RUGBY_G3C_KP          ,USP_RUGBY_G3C_KP2          ,USP_RUGBY_G3C_KP_MX          ,USP_RUGBY_G3C_KP_OR          ,USP_RUGBY_G3C_KP2_MX          ,USP_RUGBY_G3C_KP2_OR);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_AMCU ,USP_RUGBY_G3C_KP_BLK_AMCU ,USP_RUGBY_G3C_KP2_BLK_AMCU ,USP_RUGBY_G3C_KP_MX_BLK_AMCU ,USP_RUGBY_G3C_KP_OR_BLK_AMCU ,USP_RUGBY_G3C_KP2_MX_BLK_AMCU ,USP_RUGBY_G3C_KP2_OR_BLK_AMCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_AOR1 ,USP_RUGBY_G3C_KP_BLK_AOR1 ,USP_RUGBY_G3C_KP2_BLK_AOR1 ,USP_RUGBY_G3C_KP_MX_BLK_AOR1 ,USP_RUGBY_G3C_KP_OR_BLK_AOR1 ,USP_RUGBY_G3C_KP2_MX_BLK_AOR1 ,USP_RUGBY_G3C_KP2_OR_BLK_AOR1);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_AOR2 ,USP_RUGBY_G3C_KP_BLK_AOR2 ,USP_RUGBY_G3C_KP2_BLK_AOR2 ,USP_RUGBY_G3C_KP_MX_BLK_AOR2 ,USP_RUGBY_G3C_KP_OR_BLK_AOR2 ,USP_RUGBY_G3C_KP2_MX_BLK_AOR2 ,USP_RUGBY_G3C_KP2_OR_BLK_AOR2);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_DCU  ,USP_RUGBY_G3C_KP_BLK_DCU  ,USP_RUGBY_G3C_KP2_BLK_DCU  ,USP_RUGBY_G3C_KP_MX_BLK_DCU  ,USP_RUGBY_G3C_KP_OR_BLK_DCU  ,USP_RUGBY_G3C_KP2_MX_BLK_DCU  ,USP_RUGBY_G3C_KP2_OR_BLK_DCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_GRY  ,USP_RUGBY_G3C_KP_BLK_GRY  ,USP_RUGBY_G3C_KP2_BLK_GRY  ,USP_RUGBY_G3C_KP_MX_BLK_GRY  ,USP_RUGBY_G3C_KP_OR_BLK_GRY  ,USP_RUGBY_G3C_KP2_MX_BLK_GRY  ,USP_RUGBY_G3C_KP2_OR_BLK_GRY);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_KHK  ,USP_RUGBY_G3C_KP_BLK_KHK  ,USP_RUGBY_G3C_KP2_BLK_KHK  ,USP_RUGBY_G3C_KP_MX_BLK_KHK  ,USP_RUGBY_G3C_KP_OR_BLK_KHK  ,USP_RUGBY_G3C_KP2_MX_BLK_KHK  ,USP_RUGBY_G3C_KP2_OR_BLK_KHK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_M81  ,USP_RUGBY_G3C_KP_BLK_M81  ,USP_RUGBY_G3C_KP2_BLK_M81  ,USP_RUGBY_G3C_KP_MX_BLK_M81  ,USP_RUGBY_G3C_KP_OR_BLK_M81  ,USP_RUGBY_G3C_KP2_MX_BLK_M81  ,USP_RUGBY_G3C_KP2_OR_BLK_M81);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MC   ,USP_RUGBY_G3C_KP_BLK_MC   ,USP_RUGBY_G3C_KP2_BLK_MC   ,USP_RUGBY_G3C_KP_MX_BLK_MC   ,USP_RUGBY_G3C_KP_OR_BLK_MC   ,USP_RUGBY_G3C_KP2_MX_BLK_MC   ,USP_RUGBY_G3C_KP2_OR_BLK_MC);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCB  ,USP_RUGBY_G3C_KP_BLK_MCB  ,USP_RUGBY_G3C_KP2_BLK_MCB  ,USP_RUGBY_G3C_KP_MX_BLK_MCB  ,USP_RUGBY_G3C_KP_OR_BLK_MCB  ,USP_RUGBY_G3C_KP2_MX_BLK_MCB  ,USP_RUGBY_G3C_KP2_OR_BLK_MCB);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCD  ,USP_RUGBY_G3C_KP_BLK_MCD  ,USP_RUGBY_G3C_KP2_BLK_MCD  ,USP_RUGBY_G3C_KP_MX_BLK_MCD  ,USP_RUGBY_G3C_KP_OR_BLK_MCD  ,USP_RUGBY_G3C_KP2_MX_BLK_MCD  ,USP_RUGBY_G3C_KP2_OR_BLK_MCD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCT  ,USP_RUGBY_G3C_KP_BLK_MCT  ,USP_RUGBY_G3C_KP2_BLK_MCT  ,USP_RUGBY_G3C_KP_MX_BLK_MCT  ,USP_RUGBY_G3C_KP_OR_BLK_MCT  ,USP_RUGBY_G3C_KP2_MX_BLK_MCT  ,USP_RUGBY_G3C_KP2_OR_BLK_MCT);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MCW  ,USP_RUGBY_G3C_KP_BLK_MCW  ,USP_RUGBY_G3C_KP2_BLK_MCW  ,USP_RUGBY_G3C_KP_MX_BLK_MCW  ,USP_RUGBY_G3C_KP_OR_BLK_MCW  ,USP_RUGBY_G3C_KP2_MX_BLK_MCW  ,USP_RUGBY_G3C_KP2_OR_BLK_MCW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MM14 ,USP_RUGBY_G3C_KP_BLK_MM14 ,USP_RUGBY_G3C_KP2_BLK_MM14 ,USP_RUGBY_G3C_KP_MX_BLK_MM14 ,USP_RUGBY_G3C_KP_OR_BLK_MM14 ,USP_RUGBY_G3C_KP2_MX_BLK_MM14 ,USP_RUGBY_G3C_KP2_OR_BLK_MM14);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MPD  ,USP_RUGBY_G3C_KP_BLK_MPD  ,USP_RUGBY_G3C_KP2_BLK_MPD  ,USP_RUGBY_G3C_KP_MX_BLK_MPD  ,USP_RUGBY_G3C_KP_OR_BLK_MPD  ,USP_RUGBY_G3C_KP2_MX_BLK_MPD  ,USP_RUGBY_G3C_KP2_OR_BLK_MPD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MPW  ,USP_RUGBY_G3C_KP_BLK_MPW  ,USP_RUGBY_G3C_KP2_BLK_MPW  ,USP_RUGBY_G3C_KP_MX_BLK_MPW  ,USP_RUGBY_G3C_KP_OR_BLK_MPW  ,USP_RUGBY_G3C_KP2_MX_BLK_MPW  ,USP_RUGBY_G3C_KP2_OR_BLK_MPW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MTN  ,USP_RUGBY_G3C_KP_BLK_MTN  ,USP_RUGBY_G3C_KP2_BLK_MTN  ,USP_RUGBY_G3C_KP_MX_BLK_MTN  ,USP_RUGBY_G3C_KP_OR_BLK_MTN  ,USP_RUGBY_G3C_KP2_MX_BLK_MTN  ,USP_RUGBY_G3C_KP2_OR_BLK_MTN);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_MTP  ,USP_RUGBY_G3C_KP_BLK_MTP  ,USP_RUGBY_G3C_KP2_BLK_MTP  ,USP_RUGBY_G3C_KP_MX_BLK_MTP  ,USP_RUGBY_G3C_KP_OR_BLK_MTP  ,USP_RUGBY_G3C_KP2_MX_BLK_MTP  ,USP_RUGBY_G3C_KP2_OR_BLK_MTP);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_NAV  ,USP_RUGBY_G3C_KP_BLK_NAV  ,USP_RUGBY_G3C_KP2_BLK_NAV  ,USP_RUGBY_G3C_KP_MX_BLK_NAV  ,USP_RUGBY_G3C_KP_OR_BLK_NAV  ,USP_RUGBY_G3C_KP2_MX_BLK_NAV  ,USP_RUGBY_G3C_KP2_OR_BLK_NAV);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_RBS  ,USP_RUGBY_G3C_KP_BLK_RBS  ,USP_RUGBY_G3C_KP2_BLK_RBS  ,USP_RUGBY_G3C_KP_MX_BLK_RBS  ,USP_RUGBY_G3C_KP_OR_BLK_RBS  ,USP_RUGBY_G3C_KP2_MX_BLK_RBS  ,USP_RUGBY_G3C_KP2_OR_BLK_RBS);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_RGR  ,USP_RUGBY_G3C_KP_BLK_RGR  ,USP_RUGBY_G3C_KP2_BLK_RGR  ,USP_RUGBY_G3C_KP_MX_BLK_RGR  ,USP_RUGBY_G3C_KP_OR_BLK_RGR  ,USP_RUGBY_G3C_KP2_MX_BLK_RGR  ,USP_RUGBY_G3C_KP2_OR_BLK_RGR);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_TSD  ,USP_RUGBY_G3C_KP_BLK_TSD  ,USP_RUGBY_G3C_KP2_BLK_TSD  ,USP_RUGBY_G3C_KP_MX_BLK_TSD  ,USP_RUGBY_G3C_KP_OR_BLK_TSD  ,USP_RUGBY_G3C_KP2_MX_BLK_TSD  ,USP_RUGBY_G3C_KP2_OR_BLK_TSD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_BLK_TSW  ,USP_RUGBY_G3C_KP_BLK_TSW  ,USP_RUGBY_G3C_KP2_BLK_TSW  ,USP_RUGBY_G3C_KP_MX_BLK_TSW  ,USP_RUGBY_G3C_KP_OR_BLK_TSW  ,USP_RUGBY_G3C_KP2_MX_BLK_TSW  ,USP_RUGBY_G3C_KP2_OR_BLK_TSW);

USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_BLK  ,USP_RUGBY_G3C_KP_CBR_BLK  ,USP_RUGBY_G3C_KP2_CBR_BLK  ,USP_RUGBY_G3C_KP_MX_CBR_BLK  ,USP_RUGBY_G3C_KP_OR_CBR_BLK  ,USP_RUGBY_G3C_KP2_MX_CBR_BLK  ,USP_RUGBY_G3C_KP2_OR_CBR_BLK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_AMCU ,USP_RUGBY_G3C_KP_CBR_AMCU ,USP_RUGBY_G3C_KP2_CBR_AMCU ,USP_RUGBY_G3C_KP_MX_CBR_AMCU ,USP_RUGBY_G3C_KP_OR_CBR_AMCU ,USP_RUGBY_G3C_KP2_MX_CBR_AMCU ,USP_RUGBY_G3C_KP2_OR_CBR_AMCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_AOR1 ,USP_RUGBY_G3C_KP_CBR_AOR1 ,USP_RUGBY_G3C_KP2_CBR_AOR1 ,USP_RUGBY_G3C_KP_MX_CBR_AOR1 ,USP_RUGBY_G3C_KP_OR_CBR_AOR1 ,USP_RUGBY_G3C_KP2_MX_CBR_AOR1 ,USP_RUGBY_G3C_KP2_OR_CBR_AOR1);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_AOR2 ,USP_RUGBY_G3C_KP_CBR_AOR2 ,USP_RUGBY_G3C_KP2_CBR_AOR2 ,USP_RUGBY_G3C_KP_MX_CBR_AOR2 ,USP_RUGBY_G3C_KP_OR_CBR_AOR2 ,USP_RUGBY_G3C_KP2_MX_CBR_AOR2 ,USP_RUGBY_G3C_KP2_OR_CBR_AOR2);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_DCU  ,USP_RUGBY_G3C_KP_CBR_DCU  ,USP_RUGBY_G3C_KP2_CBR_DCU  ,USP_RUGBY_G3C_KP_MX_CBR_DCU  ,USP_RUGBY_G3C_KP_OR_CBR_DCU  ,USP_RUGBY_G3C_KP2_MX_CBR_DCU  ,USP_RUGBY_G3C_KP2_OR_CBR_DCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_GRY  ,USP_RUGBY_G3C_KP_CBR_GRY  ,USP_RUGBY_G3C_KP2_CBR_GRY  ,USP_RUGBY_G3C_KP_MX_CBR_GRY  ,USP_RUGBY_G3C_KP_OR_CBR_GRY  ,USP_RUGBY_G3C_KP2_MX_CBR_GRY  ,USP_RUGBY_G3C_KP2_OR_CBR_GRY);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_KHK  ,USP_RUGBY_G3C_KP_CBR_KHK  ,USP_RUGBY_G3C_KP2_CBR_KHK  ,USP_RUGBY_G3C_KP_MX_CBR_KHK  ,USP_RUGBY_G3C_KP_OR_CBR_KHK  ,USP_RUGBY_G3C_KP2_MX_CBR_KHK  ,USP_RUGBY_G3C_KP2_OR_CBR_KHK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_M81  ,USP_RUGBY_G3C_KP_CBR_M81  ,USP_RUGBY_G3C_KP2_CBR_M81  ,USP_RUGBY_G3C_KP_MX_CBR_M81  ,USP_RUGBY_G3C_KP_OR_CBR_M81  ,USP_RUGBY_G3C_KP2_MX_CBR_M81  ,USP_RUGBY_G3C_KP2_OR_CBR_M81);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MC   ,USP_RUGBY_G3C_KP_CBR_MC   ,USP_RUGBY_G3C_KP2_CBR_MC   ,USP_RUGBY_G3C_KP_MX_CBR_MC   ,USP_RUGBY_G3C_KP_OR_CBR_MC   ,USP_RUGBY_G3C_KP2_MX_CBR_MC   ,USP_RUGBY_G3C_KP2_OR_CBR_MC);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MCB  ,USP_RUGBY_G3C_KP_CBR_MCB  ,USP_RUGBY_G3C_KP2_CBR_MCB  ,USP_RUGBY_G3C_KP_MX_CBR_MCB  ,USP_RUGBY_G3C_KP_OR_CBR_MCB  ,USP_RUGBY_G3C_KP2_MX_CBR_MCB  ,USP_RUGBY_G3C_KP2_OR_CBR_MCB);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MCD  ,USP_RUGBY_G3C_KP_CBR_MCD  ,USP_RUGBY_G3C_KP2_CBR_MCD  ,USP_RUGBY_G3C_KP_MX_CBR_MCD  ,USP_RUGBY_G3C_KP_OR_CBR_MCD  ,USP_RUGBY_G3C_KP2_MX_CBR_MCD  ,USP_RUGBY_G3C_KP2_OR_CBR_MCD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MCT  ,USP_RUGBY_G3C_KP_CBR_MCT  ,USP_RUGBY_G3C_KP2_CBR_MCT  ,USP_RUGBY_G3C_KP_MX_CBR_MCT  ,USP_RUGBY_G3C_KP_OR_CBR_MCT  ,USP_RUGBY_G3C_KP2_MX_CBR_MCT  ,USP_RUGBY_G3C_KP2_OR_CBR_MCT);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MCW  ,USP_RUGBY_G3C_KP_CBR_MCW  ,USP_RUGBY_G3C_KP2_CBR_MCW  ,USP_RUGBY_G3C_KP_MX_CBR_MCW  ,USP_RUGBY_G3C_KP_OR_CBR_MCW  ,USP_RUGBY_G3C_KP2_MX_CBR_MCW  ,USP_RUGBY_G3C_KP2_OR_CBR_MCW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MM14 ,USP_RUGBY_G3C_KP_CBR_MM14 ,USP_RUGBY_G3C_KP2_CBR_MM14 ,USP_RUGBY_G3C_KP_MX_CBR_MM14 ,USP_RUGBY_G3C_KP_OR_CBR_MM14 ,USP_RUGBY_G3C_KP2_MX_CBR_MM14 ,USP_RUGBY_G3C_KP2_OR_CBR_MM14);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MPD  ,USP_RUGBY_G3C_KP_CBR_MPD  ,USP_RUGBY_G3C_KP2_CBR_MPD  ,USP_RUGBY_G3C_KP_MX_CBR_MPD  ,USP_RUGBY_G3C_KP_OR_CBR_MPD  ,USP_RUGBY_G3C_KP2_MX_CBR_MPD  ,USP_RUGBY_G3C_KP2_OR_CBR_MPD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MPW  ,USP_RUGBY_G3C_KP_CBR_MPW  ,USP_RUGBY_G3C_KP2_CBR_MPW  ,USP_RUGBY_G3C_KP_MX_CBR_MPW  ,USP_RUGBY_G3C_KP_OR_CBR_MPW  ,USP_RUGBY_G3C_KP2_MX_CBR_MPW  ,USP_RUGBY_G3C_KP2_OR_CBR_MPW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MTN  ,USP_RUGBY_G3C_KP_CBR_MTN  ,USP_RUGBY_G3C_KP2_CBR_MTN  ,USP_RUGBY_G3C_KP_MX_CBR_MTN  ,USP_RUGBY_G3C_KP_OR_CBR_MTN  ,USP_RUGBY_G3C_KP2_MX_CBR_MTN  ,USP_RUGBY_G3C_KP2_OR_CBR_MTN);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_MTP  ,USP_RUGBY_G3C_KP_CBR_MTP  ,USP_RUGBY_G3C_KP2_CBR_MTP  ,USP_RUGBY_G3C_KP_MX_CBR_MTP  ,USP_RUGBY_G3C_KP_OR_CBR_MTP  ,USP_RUGBY_G3C_KP2_MX_CBR_MTP  ,USP_RUGBY_G3C_KP2_OR_CBR_MTP);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_NAV  ,USP_RUGBY_G3C_KP_CBR_NAV  ,USP_RUGBY_G3C_KP2_CBR_NAV  ,USP_RUGBY_G3C_KP_MX_CBR_NAV  ,USP_RUGBY_G3C_KP_OR_CBR_NAV  ,USP_RUGBY_G3C_KP2_MX_CBR_NAV  ,USP_RUGBY_G3C_KP2_OR_CBR_NAV);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_RBS  ,USP_RUGBY_G3C_KP_CBR_RBS  ,USP_RUGBY_G3C_KP2_CBR_RBS  ,USP_RUGBY_G3C_KP_MX_CBR_RBS  ,USP_RUGBY_G3C_KP_OR_CBR_RBS  ,USP_RUGBY_G3C_KP2_MX_CBR_RBS  ,USP_RUGBY_G3C_KP2_OR_CBR_RBS);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_RGR  ,USP_RUGBY_G3C_KP_CBR_RGR  ,USP_RUGBY_G3C_KP2_CBR_RGR  ,USP_RUGBY_G3C_KP_MX_CBR_RGR  ,USP_RUGBY_G3C_KP_OR_CBR_RGR  ,USP_RUGBY_G3C_KP2_MX_CBR_RGR  ,USP_RUGBY_G3C_KP2_OR_CBR_RGR);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_TSD  ,USP_RUGBY_G3C_KP_CBR_TSD  ,USP_RUGBY_G3C_KP2_CBR_TSD  ,USP_RUGBY_G3C_KP_MX_CBR_TSD  ,USP_RUGBY_G3C_KP_OR_CBR_TSD  ,USP_RUGBY_G3C_KP2_MX_CBR_TSD  ,USP_RUGBY_G3C_KP2_OR_CBR_TSD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_CBR_TSW  ,USP_RUGBY_G3C_KP_CBR_TSW  ,USP_RUGBY_G3C_KP2_CBR_TSW  ,USP_RUGBY_G3C_KP_MX_CBR_TSW  ,USP_RUGBY_G3C_KP_OR_CBR_TSW  ,USP_RUGBY_G3C_KP2_MX_CBR_TSW  ,USP_RUGBY_G3C_KP2_OR_CBR_TSW);

USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY      ,USP_RUGBY_G3C_KP_GRY       ,USP_RUGBY_G3C_KP2_GRY      ,USP_RUGBY_G3C_KP_MX_GRY      ,USP_RUGBY_G3C_KP_OR_GRY      ,USP_RUGBY_G3C_KP2_MX_GRY     ,USP_RUGBY_G3C_KP2_OR_GRY);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_AMCU ,USP_RUGBY_G3C_KP_GRY_AMCU ,USP_RUGBY_G3C_KP2_GRY_AMCU ,USP_RUGBY_G3C_KP_MX_GRY_AMCU ,USP_RUGBY_G3C_KP_OR_GRY_AMCU ,USP_RUGBY_G3C_KP2_MX_GRY_AMCU ,USP_RUGBY_G3C_KP2_OR_GRY_AMCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_AOR1 ,USP_RUGBY_G3C_KP_GRY_AOR1 ,USP_RUGBY_G3C_KP2_GRY_AOR1 ,USP_RUGBY_G3C_KP_MX_GRY_AOR1 ,USP_RUGBY_G3C_KP_OR_GRY_AOR1 ,USP_RUGBY_G3C_KP2_MX_GRY_AOR1 ,USP_RUGBY_G3C_KP2_OR_GRY_AOR1);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_AOR2 ,USP_RUGBY_G3C_KP_GRY_AOR2 ,USP_RUGBY_G3C_KP2_GRY_AOR2 ,USP_RUGBY_G3C_KP_MX_GRY_AOR2 ,USP_RUGBY_G3C_KP_OR_GRY_AOR2 ,USP_RUGBY_G3C_KP2_MX_GRY_AOR2 ,USP_RUGBY_G3C_KP2_OR_GRY_AOR2);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_DCU  ,USP_RUGBY_G3C_KP_GRY_DCU  ,USP_RUGBY_G3C_KP2_GRY_DCU  ,USP_RUGBY_G3C_KP_MX_GRY_DCU  ,USP_RUGBY_G3C_KP_OR_GRY_DCU  ,USP_RUGBY_G3C_KP2_MX_GRY_DCU  ,USP_RUGBY_G3C_KP2_OR_GRY_DCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_BLK  ,USP_RUGBY_G3C_KP_GRY_BLK  ,USP_RUGBY_G3C_KP2_GRY_BLK  ,USP_RUGBY_G3C_KP_MX_GRY_BLK  ,USP_RUGBY_G3C_KP_OR_GRY_BLK  ,USP_RUGBY_G3C_KP2_MX_GRY_BLK  ,USP_RUGBY_G3C_KP2_OR_GRY_BLK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_KHK  ,USP_RUGBY_G3C_KP_GRY_KHK  ,USP_RUGBY_G3C_KP2_GRY_KHK  ,USP_RUGBY_G3C_KP_MX_GRY_KHK  ,USP_RUGBY_G3C_KP_OR_GRY_KHK  ,USP_RUGBY_G3C_KP2_MX_GRY_KHK  ,USP_RUGBY_G3C_KP2_OR_GRY_KHK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_M81  ,USP_RUGBY_G3C_KP_GRY_M81  ,USP_RUGBY_G3C_KP2_GRY_M81  ,USP_RUGBY_G3C_KP_MX_GRY_M81  ,USP_RUGBY_G3C_KP_OR_GRY_M81  ,USP_RUGBY_G3C_KP2_MX_GRY_M81  ,USP_RUGBY_G3C_KP2_OR_GRY_M81);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MC   ,USP_RUGBY_G3C_KP_GRY_MC   ,USP_RUGBY_G3C_KP2_GRY_MC   ,USP_RUGBY_G3C_KP_MX_GRY_MC   ,USP_RUGBY_G3C_KP_OR_GRY_MC   ,USP_RUGBY_G3C_KP2_MX_GRY_MC   ,USP_RUGBY_G3C_KP2_OR_GRY_MC);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MCB  ,USP_RUGBY_G3C_KP_GRY_MCB  ,USP_RUGBY_G3C_KP2_GRY_MCB  ,USP_RUGBY_G3C_KP_MX_GRY_MCB  ,USP_RUGBY_G3C_KP_OR_GRY_MCB  ,USP_RUGBY_G3C_KP2_MX_GRY_MCB  ,USP_RUGBY_G3C_KP2_OR_GRY_MCB);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MCD  ,USP_RUGBY_G3C_KP_GRY_MCD  ,USP_RUGBY_G3C_KP2_GRY_MCD  ,USP_RUGBY_G3C_KP_MX_GRY_MCD  ,USP_RUGBY_G3C_KP_OR_GRY_MCD  ,USP_RUGBY_G3C_KP2_MX_GRY_MCD  ,USP_RUGBY_G3C_KP2_OR_GRY_MCD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MCT  ,USP_RUGBY_G3C_KP_GRY_MCT  ,USP_RUGBY_G3C_KP2_GRY_MCT  ,USP_RUGBY_G3C_KP_MX_GRY_MCT  ,USP_RUGBY_G3C_KP_OR_GRY_MCT  ,USP_RUGBY_G3C_KP2_MX_GRY_MCT  ,USP_RUGBY_G3C_KP2_OR_GRY_MCT);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MCW  ,USP_RUGBY_G3C_KP_GRY_MCW  ,USP_RUGBY_G3C_KP2_GRY_MCW  ,USP_RUGBY_G3C_KP_MX_GRY_MCW  ,USP_RUGBY_G3C_KP_OR_GRY_MCW  ,USP_RUGBY_G3C_KP2_MX_GRY_MCW  ,USP_RUGBY_G3C_KP2_OR_GRY_MCW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MM14 ,USP_RUGBY_G3C_KP_GRY_MM14 ,USP_RUGBY_G3C_KP2_GRY_MM14 ,USP_RUGBY_G3C_KP_MX_GRY_MM14 ,USP_RUGBY_G3C_KP_OR_GRY_MM14 ,USP_RUGBY_G3C_KP2_MX_GRY_MM14 ,USP_RUGBY_G3C_KP2_OR_GRY_MM14);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MPD  ,USP_RUGBY_G3C_KP_GRY_MPD  ,USP_RUGBY_G3C_KP2_GRY_MPD  ,USP_RUGBY_G3C_KP_MX_GRY_MPD  ,USP_RUGBY_G3C_KP_OR_GRY_MPD  ,USP_RUGBY_G3C_KP2_MX_GRY_MPD  ,USP_RUGBY_G3C_KP2_OR_GRY_MPD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MPW  ,USP_RUGBY_G3C_KP_GRY_MPW  ,USP_RUGBY_G3C_KP2_GRY_MPW  ,USP_RUGBY_G3C_KP_MX_GRY_MPW  ,USP_RUGBY_G3C_KP_OR_GRY_MPW  ,USP_RUGBY_G3C_KP2_MX_GRY_MPW  ,USP_RUGBY_G3C_KP2_OR_GRY_MPW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MTN  ,USP_RUGBY_G3C_KP_GRY_MTN  ,USP_RUGBY_G3C_KP2_GRY_MTN  ,USP_RUGBY_G3C_KP_MX_GRY_MTN  ,USP_RUGBY_G3C_KP_OR_GRY_MTN  ,USP_RUGBY_G3C_KP2_MX_GRY_MTN  ,USP_RUGBY_G3C_KP2_OR_GRY_MTN);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_MTP  ,USP_RUGBY_G3C_KP_GRY_MTP  ,USP_RUGBY_G3C_KP2_GRY_MTP  ,USP_RUGBY_G3C_KP_MX_GRY_MTP  ,USP_RUGBY_G3C_KP_OR_GRY_MTP  ,USP_RUGBY_G3C_KP2_MX_GRY_MTP  ,USP_RUGBY_G3C_KP2_OR_GRY_MTP);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_NAV  ,USP_RUGBY_G3C_KP_GRY_NAV  ,USP_RUGBY_G3C_KP2_GRY_NAV  ,USP_RUGBY_G3C_KP_MX_GRY_NAV  ,USP_RUGBY_G3C_KP_OR_GRY_NAV  ,USP_RUGBY_G3C_KP2_MX_GRY_NAV  ,USP_RUGBY_G3C_KP2_OR_GRY_NAV);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_RBS  ,USP_RUGBY_G3C_KP_GRY_RBS  ,USP_RUGBY_G3C_KP2_GRY_RBS  ,USP_RUGBY_G3C_KP_MX_GRY_RBS  ,USP_RUGBY_G3C_KP_OR_GRY_RBS  ,USP_RUGBY_G3C_KP2_MX_GRY_RBS  ,USP_RUGBY_G3C_KP2_OR_GRY_RBS);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_RGR  ,USP_RUGBY_G3C_KP_GRY_RGR  ,USP_RUGBY_G3C_KP2_GRY_RGR  ,USP_RUGBY_G3C_KP_MX_GRY_RGR  ,USP_RUGBY_G3C_KP_OR_GRY_RGR  ,USP_RUGBY_G3C_KP2_MX_GRY_RGR  ,USP_RUGBY_G3C_KP2_OR_GRY_RGR);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_TSD  ,USP_RUGBY_G3C_KP_GRY_TSD  ,USP_RUGBY_G3C_KP2_GRY_TSD  ,USP_RUGBY_G3C_KP_MX_GRY_TSD  ,USP_RUGBY_G3C_KP_OR_GRY_TSD  ,USP_RUGBY_G3C_KP2_MX_GRY_TSD  ,USP_RUGBY_G3C_KP2_OR_GRY_TSD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_GRY_TSW  ,USP_RUGBY_G3C_KP_GRY_TSW  ,USP_RUGBY_G3C_KP2_GRY_TSW  ,USP_RUGBY_G3C_KP_MX_GRY_TSW  ,USP_RUGBY_G3C_KP_OR_GRY_TSW  ,USP_RUGBY_G3C_KP2_MX_GRY_TSW  ,USP_RUGBY_G3C_KP2_OR_GRY_TSW);

USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR      ,USP_RUGBY_G3C_KP_RGR       ,USP_RUGBY_G3C_KP2_RGR      ,USP_RUGBY_G3C_KP_MX_RGR      ,USP_RUGBY_G3C_KP_OR_RGR      ,USP_RUGBY_G3C_KP2_MX_RGR     ,USP_RUGBY_G3C_KP2_OR_RGR);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_AMCU ,USP_RUGBY_G3C_KP_RGR_AMCU ,USP_RUGBY_G3C_KP2_RGR_AMCU ,USP_RUGBY_G3C_KP_MX_RGR_AMCU ,USP_RUGBY_G3C_KP_OR_RGR_AMCU ,USP_RUGBY_G3C_KP2_MX_RGR_AMCU ,USP_RUGBY_G3C_KP2_OR_RGR_AMCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_AOR1 ,USP_RUGBY_G3C_KP_RGR_AOR1 ,USP_RUGBY_G3C_KP2_RGR_AOR1 ,USP_RUGBY_G3C_KP_MX_RGR_AOR1 ,USP_RUGBY_G3C_KP_OR_RGR_AOR1 ,USP_RUGBY_G3C_KP2_MX_RGR_AOR1 ,USP_RUGBY_G3C_KP2_OR_RGR_AOR1);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_AOR2 ,USP_RUGBY_G3C_KP_RGR_AOR2 ,USP_RUGBY_G3C_KP2_RGR_AOR2 ,USP_RUGBY_G3C_KP_MX_RGR_AOR2 ,USP_RUGBY_G3C_KP_OR_RGR_AOR2 ,USP_RUGBY_G3C_KP2_MX_RGR_AOR2 ,USP_RUGBY_G3C_KP2_OR_RGR_AOR2);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_BLK  ,USP_RUGBY_G3C_KP_RGR_BLK  ,USP_RUGBY_G3C_KP2_RGR_BLK  ,USP_RUGBY_G3C_KP_MX_RGR_BLK  ,USP_RUGBY_G3C_KP_OR_RGR_BLK  ,USP_RUGBY_G3C_KP2_MX_RGR_BLK  ,USP_RUGBY_G3C_KP2_OR_RGR_BLK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_DCU  ,USP_RUGBY_G3C_KP_RGR_DCU  ,USP_RUGBY_G3C_KP2_RGR_DCU  ,USP_RUGBY_G3C_KP_MX_RGR_DCU  ,USP_RUGBY_G3C_KP_OR_RGR_DCU  ,USP_RUGBY_G3C_KP2_MX_RGR_DCU  ,USP_RUGBY_G3C_KP2_OR_RGR_DCU);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_GRY  ,USP_RUGBY_G3C_KP_RGR_GRY  ,USP_RUGBY_G3C_KP2_RGR_GRY  ,USP_RUGBY_G3C_KP_MX_RGR_GRY  ,USP_RUGBY_G3C_KP_OR_RGR_GRY  ,USP_RUGBY_G3C_KP2_MX_RGR_GRY  ,USP_RUGBY_G3C_KP2_OR_RGR_GRY);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_KHK  ,USP_RUGBY_G3C_KP_RGR_KHK  ,USP_RUGBY_G3C_KP2_RGR_KHK  ,USP_RUGBY_G3C_KP_MX_RGR_KHK  ,USP_RUGBY_G3C_KP_OR_RGR_KHK  ,USP_RUGBY_G3C_KP2_MX_RGR_KHK  ,USP_RUGBY_G3C_KP2_OR_RGR_KHK);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_M81  ,USP_RUGBY_G3C_KP_RGR_M81  ,USP_RUGBY_G3C_KP2_RGR_M81  ,USP_RUGBY_G3C_KP_MX_RGR_M81  ,USP_RUGBY_G3C_KP_OR_RGR_M81  ,USP_RUGBY_G3C_KP2_MX_RGR_M81  ,USP_RUGBY_G3C_KP2_OR_RGR_M81);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MC   ,USP_RUGBY_G3C_KP_RGR_MC   ,USP_RUGBY_G3C_KP2_RGR_MC   ,USP_RUGBY_G3C_KP_MX_RGR_MC   ,USP_RUGBY_G3C_KP_OR_RGR_MC   ,USP_RUGBY_G3C_KP2_MX_RGR_MC   ,USP_RUGBY_G3C_KP2_OR_RGR_MC);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MCB  ,USP_RUGBY_G3C_KP_RGR_MCB  ,USP_RUGBY_G3C_KP2_RGR_MCB  ,USP_RUGBY_G3C_KP_MX_RGR_MCB  ,USP_RUGBY_G3C_KP_OR_RGR_MCB  ,USP_RUGBY_G3C_KP2_MX_RGR_MCB  ,USP_RUGBY_G3C_KP2_OR_RGR_MCB);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MCD  ,USP_RUGBY_G3C_KP_RGR_MCD  ,USP_RUGBY_G3C_KP2_RGR_MCD  ,USP_RUGBY_G3C_KP_MX_RGR_MCD  ,USP_RUGBY_G3C_KP_OR_RGR_MCD  ,USP_RUGBY_G3C_KP2_MX_RGR_MCD  ,USP_RUGBY_G3C_KP2_OR_RGR_MCD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MCT  ,USP_RUGBY_G3C_KP_RGR_MCT  ,USP_RUGBY_G3C_KP2_RGR_MCT  ,USP_RUGBY_G3C_KP_MX_RGR_MCT  ,USP_RUGBY_G3C_KP_OR_RGR_MCT  ,USP_RUGBY_G3C_KP2_MX_RGR_MCT  ,USP_RUGBY_G3C_KP2_OR_RGR_MCT);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MCW  ,USP_RUGBY_G3C_KP_RGR_MCW  ,USP_RUGBY_G3C_KP2_RGR_MCW  ,USP_RUGBY_G3C_KP_MX_RGR_MCW  ,USP_RUGBY_G3C_KP_OR_RGR_MCW  ,USP_RUGBY_G3C_KP2_MX_RGR_MCW  ,USP_RUGBY_G3C_KP2_OR_RGR_MCW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MM14 ,USP_RUGBY_G3C_KP_RGR_MM14 ,USP_RUGBY_G3C_KP2_RGR_MM14 ,USP_RUGBY_G3C_KP_MX_RGR_MM14 ,USP_RUGBY_G3C_KP_OR_RGR_MM14 ,USP_RUGBY_G3C_KP2_MX_RGR_MM14 ,USP_RUGBY_G3C_KP2_OR_RGR_MM14);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MPD  ,USP_RUGBY_G3C_KP_RGR_MPD  ,USP_RUGBY_G3C_KP2_RGR_MPD  ,USP_RUGBY_G3C_KP_MX_RGR_MPD  ,USP_RUGBY_G3C_KP_OR_RGR_MPD  ,USP_RUGBY_G3C_KP2_MX_RGR_MPD  ,USP_RUGBY_G3C_KP2_OR_RGR_MPD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MPW  ,USP_RUGBY_G3C_KP_RGR_MPW  ,USP_RUGBY_G3C_KP2_RGR_MPW  ,USP_RUGBY_G3C_KP_MX_RGR_MPW  ,USP_RUGBY_G3C_KP_OR_RGR_MPW  ,USP_RUGBY_G3C_KP2_MX_RGR_MPW  ,USP_RUGBY_G3C_KP2_OR_RGR_MPW);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MTN  ,USP_RUGBY_G3C_KP_RGR_MTN  ,USP_RUGBY_G3C_KP2_RGR_MTN  ,USP_RUGBY_G3C_KP_MX_RGR_MTN  ,USP_RUGBY_G3C_KP_OR_RGR_MTN  ,USP_RUGBY_G3C_KP2_MX_RGR_MTN  ,USP_RUGBY_G3C_KP2_OR_RGR_MTN);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_MTP  ,USP_RUGBY_G3C_KP_RGR_MTP  ,USP_RUGBY_G3C_KP2_RGR_MTP  ,USP_RUGBY_G3C_KP_MX_RGR_MTP  ,USP_RUGBY_G3C_KP_OR_RGR_MTP  ,USP_RUGBY_G3C_KP2_MX_RGR_MTP  ,USP_RUGBY_G3C_KP2_OR_RGR_MTP);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_NAV  ,USP_RUGBY_G3C_KP_RGR_NAV  ,USP_RUGBY_G3C_KP2_RGR_NAV  ,USP_RUGBY_G3C_KP_MX_RGR_NAV  ,USP_RUGBY_G3C_KP_OR_RGR_NAV  ,USP_RUGBY_G3C_KP2_MX_RGR_NAV  ,USP_RUGBY_G3C_KP2_OR_RGR_NAV);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_RBS  ,USP_RUGBY_G3C_KP_RGR_RBS  ,USP_RUGBY_G3C_KP2_RGR_RBS  ,USP_RUGBY_G3C_KP_MX_RGR_RBS  ,USP_RUGBY_G3C_KP_OR_RGR_RBS  ,USP_RUGBY_G3C_KP2_MX_RGR_RBS  ,USP_RUGBY_G3C_KP2_OR_RGR_RBS);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_RGR  ,USP_RUGBY_G3C_KP_RGR_RGR  ,USP_RUGBY_G3C_KP2_RGR_RGR  ,USP_RUGBY_G3C_KP_MX_RGR_RGR  ,USP_RUGBY_G3C_KP_OR_RGR_RGR  ,USP_RUGBY_G3C_KP2_MX_RGR_RGR  ,USP_RUGBY_G3C_KP2_OR_RGR_RGR);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_TSD  ,USP_RUGBY_G3C_KP_RGR_TSD  ,USP_RUGBY_G3C_KP2_RGR_TSD  ,USP_RUGBY_G3C_KP_MX_RGR_TSD  ,USP_RUGBY_G3C_KP_OR_RGR_TSD  ,USP_RUGBY_G3C_KP2_MX_RGR_TSD  ,USP_RUGBY_G3C_KP2_OR_RGR_TSD);
USP_UNIFORM_KP_GL(USP_RUGBY_G3C_RGR_TSW  ,USP_RUGBY_G3C_KP_RGR_TSW  ,USP_RUGBY_G3C_KP2_RGR_TSW  ,USP_RUGBY_G3C_KP_MX_RGR_TSW  ,USP_RUGBY_G3C_KP_OR_RGR_TSW  ,USP_RUGBY_G3C_KP2_MX_RGR_TSW  ,USP_RUGBY_G3C_KP2_OR_RGR_TSW);