#define USP_UNIFORM_GLOVES(UniformBase,UniformGloves1,Gloves1,UniformGloves2,Gloves2)\
class UniformBase: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformGloves1 {};\
        class UniformGloves2 {};\
    };\
};\
class UniformGloves1: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        components[] = {QUOTE(Gloves1)};\
    };\
};\
class UniformGloves2: ace_wardrobe_base {\
    class modifiableTo {\
        class UniformBase {};\
        components[] = {QUOTE(Gloves2)};\
    };\
}

//Uniform with Gloves
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C,USP_SOFTSHELL_G3C_MX,USP_MECHANIX,USP_SOFTSHELL_G3C_OR,USP_OVERLORD);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_BLK_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_CBR_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_GRY_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_MC_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_RGR_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP,USP_SOFTSHELL_G3C_KP_MX,USP_SOFTSHELL_G3C_KP_OR,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_AOR1,USP_SOFTSHELL_G3C_KP_MX_BLK_AOR1,USP_SOFTSHELL_G3C_KP_OR_BLK_AOR1,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_AOR2,USP_SOFTSHELL_G3C_KP_MX_BLK_AOR2,USP_SOFTSHELL_G3C_KP_OR_BLK_AOR2,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_GRY,USP_SOFTSHELL_G3C_KP_MX_BLK_GRY,USP_SOFTSHELL_G3C_KP_OR_BLK_GRY,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_KHK,USP_SOFTSHELL_G3C_KP_MX_BLK_KHK,USP_SOFTSHELL_G3C_KP_OR_BLK_KHK,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_M81,USP_SOFTSHELL_G3C_KP_MX_BLK_M81,USP_SOFTSHELL_G3C_KP_OR_BLK_M81,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_MC,USP_SOFTSHELL_G3C_KP_MX_BLK_MC,USP_SOFTSHELL_G3C_KP_OR_BLK_MC,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_MCB,USP_SOFTSHELL_G3C_KP_MX_BLK_MCB,USP_SOFTSHELL_G3C_KP_OR_BLK_MCB,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_MCD,USP_SOFTSHELL_G3C_KP_MX_BLK_MCD,USP_SOFTSHELL_G3C_KP_OR_BLK_MCD,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_MCT,USP_SOFTSHELL_G3C_KP_MX_BLK_MCT,USP_SOFTSHELL_G3C_KP_OR_BLK_MCT,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_MCW,USP_SOFTSHELL_G3C_KP_MX_BLK_MCW,USP_SOFTSHELL_G3C_KP_OR_BLK_MCW,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_NAV,USP_SOFTSHELL_G3C_KP_MX_BLK_NAV,USP_SOFTSHELL_G3C_KP_OR_BLK_NAV,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_RGR,USP_SOFTSHELL_G3C_KP_MX_BLK_RGR,USP_SOFTSHELL_G3C_KP_OR_BLK_RGR,USP_MECHANIX_BLK2,USP_OVERLORD);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_TSD,USP_SOFTSHELL_G3C_KP_MX_BLK_TSD,USP_SOFTSHELL_G3C_KP_OR_BLK_TSD,USP_MECHANIX_CBR,USP_OVERLORD_CBR);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_BLK_TSW,USP_SOFTSHELL_G3C_KP_MX_BLK_TSW,USP_SOFTSHELL_G3C_KP_OR_BLK_TSW,USP_MECHANIX,USP_OVERLORD);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_CBR_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_GRY_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_MC_TSW,,,,);

USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_AOR1,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_AOR2,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_BLK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_GRY,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_KHK,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_M81,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_MC,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_MCB,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_MCD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_MCT,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_MCW,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_NAV,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_TSD,,,,);
USP_UNIFORM_GLOVES(USP_SOFTSHELL_G3C_KP_RGR_TSW,,,,);