UNIFORM_GLOVES_ROLLED(Flex_CUP_POL_BDU_Pads,Flex_CUP_POL_BDU_Gloves_Pads,Flex_CUP_POL_BDU_Rolled_Pads,Flex_CUP_POL_BDU_Gloves_Pads_Rolled);
UNIFORM_GLOVES_ROLLED(Flex_CUP_POL_BDU,Flex_CUP_POL_BDU_Gloves,Flex_CUP_POL_BDU_Rolled,Flex_CUP_POL_BDU_Gloves_Rolled);
