UNIFORM_GLOVES_ROLLED(LDF_Combat_Uniform,LDF_Combat_Uniform_Gloves,LDF_Combat_Uniform_Rolled,LDF_Combat_Uniform_Gloves_Rolled);
UNIFORM_GLOVES_ROLLED(LDF_Combat_Uniform_Arid,LDF_Combat_Uniform_Arid_Gloves,LDF_Combat_Uniform_Arid_Rolled,LDF_Combat_Uniform_Arid_Gloves_Rolled);
