FACEMASK_GOGGLES2(UK3CB_G_Bandanna_brown_check,UK3CB_G_Bandanna_aviator_brown_check,UK3CB_G_Bandanna_shades_brown_check,G_Aviator,G_Shades_Black);
FACEMASK_GOGGLES2(UK3CB_G_Bandanna_flora_alt,UK3CB_G_Bandanna_aviator_flora_alt,UK3CB_G_Bandanna_shades_flora_alt,G_Aviator,G_Shades_Black);
FACEMASK_GOGGLES2(UK3CB_G_Bandanna_green_check,UK3CB_G_Bandanna_aviator_green_check,UK3CB_G_Bandanna_shades_green_check,G_Aviator,G_Shades_Black);
FACEMASK_GOGGLES2(UK3CB_G_Bandanna_red_check,UK3CB_G_Bandanna_aviator_red_check,UK3CB_G_Bandanna_shades_red_check,G_Aviator,G_Shades_Black);
FACEMASK_GOGGLES2(UK3CB_G_Bandanna_winter_flora_alt,UK3CB_G_Bandanna_aviator_winter_flora_alt,UK3CB_G_Bandanna_shades_winter_flora_alt,G_Aviator,G_Shades_Black);
FACEMASK_GOGGLES2(UK3CB_G_Bandanna_winter,UK3CB_G_Bandanna_aviator_winter,UK3CB_G_Bandanna_shades_white_check,G_Aviator,G_Shades_Black);
