UNIFORM_SLEEVES(NOR_Combat_Uniform_Gloves,NOR_Combat_Uniform);
UNIFORM_SLEEVES(NOR_Combat_Uniform_SOF_Gloves,NOR_Combat_Uniform_SOF);
UNIFORM_SLEEVES(NOR_Combat_Uniform_MC_Gloves,NOR_Combat_Uniform_MC);
