UNIFROM_ROLLED(U_Simc_bdu_erla,U_Simc_bdu_erla_low);
UNIFROM_ROLLED(U_Simc_bdu_26id,U_Simc_bdu_26id_trop);
UNIFROM_ROLLED(U_Simc_bdu_erla_desu,U_Simc_bdu_erla_desu_low);
UNIFROM_ROLLED(U_Simc_bdu_26id_desu,U_Simc_bdu_26id_desu_trop);
UNIFROM_ROLLED(U_Simc_bdu_erla_MC,U_Simc_bdu_erla_MC_low);
UNIFROM_ROLLED(U_Simc_bdu_erla_MC_desu,U_Simc_bdu_erla_MC_desu_low);
UNIFROM_ROLLED(U_simc_bdu_erla_MC_gas_desu,U_simc_bdu_erla_MC_gas_desu_low);
UNIFROM_ROLLED(U_simc_bdu_erla_MC_gas,U_simc_bdu_erla_MC_gas_low);
UNIFROM_ROLLED(U_Simc_bdu_eto_mc,U_Simc_bdu_eto_mc_low);
UNIFROM_ROLLED(U_Simc_bdu_eto_mc_desu,U_Simc_bdu_eto_mc_desu_low);

UNIFROM_ROLLED(U_Simc_bdu_rdf_MC_desu,U_Simc_bdu_rdf_MC_desu_trop);
UNIFROM_ROLLED(U_simc_bdu_rdf_MC_gas_desu,U_simc_bdu_rdf_MC_gas_desu_trop);
UNIFROM_ROLLED(U_Simc_bdu_rdf_MC_erdl,U_Simc_bdu_rdf_MC_erdl_trop);
UNIFROM_ROLLED(U_simc_bdu_rdf_MC_gas_erdl,U_simc_bdu_rdf_MC_gas_erdl_trop);
UNIFROM_ROLLED(U_Simc_bdu_rdf_MC,U_Simc_bdu_rdf_MC_trop);
UNIFROM_ROLLED(U_simc_bdu_rdf_MC_gas,U_simc_bdu_rdf_MC_gas_trop);
UNIFROM_ROLLED(U_Simc_bdu_rdf_MC_desu_erdl,U_Simc_bdu_rdf_MC_desu_erdl_trop);

UNIFROM_ROLLED(U_Simc_bdu_laat_blench,U_Simc_bdu_laat_blench_trop);

UNIFROM_ROLLED3(U_Simc_bdu_eto_mc,U_Simc_bdu_eto_mc_low,U_Simc_bdu_eto_mc_trop);
UNIFROM_ROLLED3(U_simc_bdu_eto_gas_mc,U_simc_bdu_eto_gas_mc_low,U_simc_bdu_eto_gas_mc_trop);
UNIFROM_ROLLED3(U_simc_bdu_erla_MC_gas,U_simc_bdu_erla_MC_gas_low,U_simc_bdu_erla_MC_gas_trop);
UNIFROM_ROLLED3(U_Simc_bdu_erla_blench,U_Simc_bdu_erla_blench_low,U_Simc_bdu_erla_blench_trop);
UNIFROM_ROLLED3(U_Simc_bdu_erla_MC,U_Simc_bdu_erla_MC_low,U_Simc_bdu_erla_MC_trop);
