BASE_PAIR(TFC_CH_BCAP_BW_AR,TFC_CH_BCAP_AR);
BASE_PAIR(TFC_CH_BCAP_BW_BLUE,TFC_CH_BCAP_BLUE);
BASE_PAIR(TFC_CH_BCAP_BW_MCAM,TFC_CH_BCAP_MCAM);
BASE_PAIR(TFC_CH_BCAP_BW_TW,TFC_CH_BCAP_TW);

HELMET_VISOR(TFC_CH_Helo_Pilot_up,TFC_AH64_Helmet);
